server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: 175.24.229.41:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'