server:
  port: 8004

spring:
  application:
    # 服务别名----注册 zookeeper 到注册中心名称
    name: cloud-provider-payment
  cloud:
    zookeeper:
      # zookeeper 主机 : 端口号
      connect-string: 175.24.229.41:2181
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql 驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.24.229.41:1617/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: W6YnvKnLzpSFNGuc.

mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 所有 pojo 别名类所在包
  type-aliases-package: com.yixihan.springcloud.pojo